name: Lint & Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: '3.11'
        cache: true

    - name: Install dependencies
      run: |
        pdm install
        pdm add --dev ruff basedpyright mypy

    - name: Run ruff linting
      run: |
        pdm run ruff check .

    - name: Check code formatting with ruff
      run: |
        pdm run ruff format --check .

    - name: Type check with basedpyright
      run: |
        pdm run basedpyright time_mode_sim/ || true  # Warning only for now

    - name: Type check with mypy
      run: |
        pdm run mypy time_mode_sim/ --ignore-missing-imports || true  # Warning only for now

    - name: Check for common issues
      run: |
        # Check for trailing whitespace
        if grep -r "[[:space:]]$" --include="*.py" time_mode_sim/ examples/; then
          echo "Error: Found trailing whitespace in Python files"
          exit 1
        fi

        # Check for unused imports
        pdm run ruff check --select F401 time_mode_sim/ examples/