name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ruff
      run: |
        pip install ruff

    - name: Run ruff check
      run: |
        ruff check . || true  # Don't fail on lint issues for now

    - name: Check Python file formatting
      run: |
        ruff format --check . || true  # Don't fail on format issues for now